# Generated by Django 4.2.5 on 2023-10-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='core_post',
        ),
    ]
