# Generated by Django 4.2.5 on 2023-10-05 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0003_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='Created',
        ),
    ]
