# Generated by Django 4.2.5 on 2023-10-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0004_rename_created_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
